setwd("C:/Thirumal/Learning/edX/The Analytics Edge/Week 03/Assignments")
#week 03, assignment 04
loans = read.csv("loans.csv")
str(loans)
table(loans$not.fully.paid)
1533/(9578)
is.na(loans$credit.policy)
sum(is.na(loans$credit.policy))
sum(is.na(loans$purpose))
sum(is.na(loans$int.rate))
sum(is.na(loans$installment))
sum(is.na(loans$log.annual.inc))
sum(is.na(loans$dti))
sum(is.na(loans$fico))
sum(is.na(loans$days.with.cr.line))
sum(is.na(loans$revol.bal))
sum(is.na(loans$revol.util))
sum(is.na(loans$inq.last.6mths))
sum(is.na(loans$delinq.2yrs))
sum(is.na(loans$pub.rec))
sum(is.na(loans$not.fully.paid))
install.packages("mice")
library(mice)
set.seed(144)
vars.for.imputation = setdiff(names(loans), "not.fully.paid")
imputed = complete(mice(loans[vars.for.imputation]))
loans[vars.for.imputation] = imputed
str(loans)
loans_imputed = read.csv("loans_imputed.csv")
str(loans_imputed)
summary(loans_imputed)
summary(loans)
loans == loans_imputed
sum(loans == loans_imputed)
sum(loans != loans_imputed)
sum(loans != loans_imputed)
loans = read.csv("loans_imputed.csv")
#replaced loans with loans_imputed.csv as we were having 115 differences in the data set
rm(loans_imputed)
set.seed(144)
split = sample.split(loans$not.fully.paid, SplitRatio = 0.7)
train = subset(loans, split == TRUE)
test = subset(loans, split == FALSE)
str(train)
model1 = glm(not.fully.paid ~ ., data=train, family="binomial")
summary(model1)
model1$coefficients
-9.316790/1000
-9.316790e-03
-9.316790e-03*-10
exp(0.0931679)
pred1 = predict(model1, newdata = test,type="response")
table(test$not.fully.paid, pred1 > 0.5)
(2400 + 3)/(2400 + 13 + 457 + 3)
table(test$not.fully.paid)
2413/(2413+460)
library(ROCR)
ROCRpred = prediction(pred1, test$not.fully.paid)
as.numeric(performance(ROCRpred, "auc")@y.values)
model2 = glm(not.fully.paid ~ int.rate, data = train, family = "binomial")
cor(train)
cor(train$int.rate, train)
cor(train$int.rate, train$*)
cor(train$int.rate, train$.)
cor(train$int.rate, train)
summary(model1)
summary(model2)
pred2 = predict(model2, newdata=test, type = "response")
summary(pred2)
table(test$not.fully.paid, pred2 > 0.5)
ROCRpred2 = prediction(pred2, test$not.fully.paid)
as.numeric(performance(ROCRpred2, "auc")@y.values)
10*exp(0.06*3)
test$profit = exp(test$int.rate*3) - 1
test$profit[test$not.fully.paid == 1] = -1
max(test$profit)
0.8894769*10
View(test)
str(test)
highinterest = subset(test, int.rate >= 0.15)
mean(highinterest$profit)
table(highinterest$not.fully.paid)
110/(327+110)
cutoff = sort(highInterest$predicted.risk, decreasing=FALSE)[100]
cutoff = sort(highinterest$predicted.risk, decreasing=FALSE)[100]
cutoff
test$predicted.risk = predict(model1, newdata = test,type="response")
cutoff = sort(highInterest$predicted.risk, decreasing=FALSE)[100]
cutoff = sort(highinterest$predicted.risk, decreasing=FALSE)[100]
str(test)
highinterest = subset(test, int.rate >= 0.15)
cutoff = sort(highinterest$predicted.risk, decreasing=FALSE)[100]
superloans = subset(highinterest, highinterest$predicted.risk <= cutoff)
sum(superloans$profit)
table(superloans$not.fully.paid)
