#week 3, assignment 2
baseball = read.csv("baseball.csv")
str(baseball)
table(baseball$Year)
ncol(table(baseball$Year))
sumtable(baseball$Year)
ncol(sumtable(baseball$Year))
summary(sumtable(baseball$Year))
summary(table(baseball$Year))
str(table(baseball$Year))
baseball$Year$attr
attr(baseball$Year)
baseball = subset(baseball, Playoffs == 1)
table(baseball$Year)
PlayoffTable = table(baseball$Year)
PlayoffTable
str(PlayoffTable)
names(PlayoffTable)
PlayoffTable(1990, 2001) PlayoffTable(c(1990, 2001)) PlayoffTable("1990", "2001") PlayoffTable(c("1990", "2001")) PlayoffTable[1990, 2001] PlayoffTable[c(1990, 2001)] PlayoffTable["1990", "2001"] PlayoffTable[c("1990", "2001")]
PlayoffTable[c("1991","2001")]
baseball$NumCompetitors = PlayoffTable[as.character(baseball$Year)]
baseball[NumCompetitors == 8]
baseball[baseball$NumCompetitors == 8]
baseball_8 = subset(baseball, NumCompetitors == 8)
baseball$WorldSeries = as.numeric(baseball$RankPlayoffs == 1)
baseball_notwin = subset(baseball, WorldSeries == 0)
baseball_notwin = subset(baseball, WorldSeries == 1)
baseball_notwin = subset(baseball, WorldSeries == 0)
model_year = glm(WorldSeries ~ Year, data = baseball, family = "binomial")
summary(model_year)
summary(glm(WorldSeries ~ RS, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ RA, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ W, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ OBP, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ SLG, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ BA, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ RankSeason, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ OOBP, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ OSLG, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ NumCompetitors, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ League, data = baseball, family = "binomial"))
multiModel = glm(WorldSeries ~ Year + RA + RankSeason + NumCompetitors, data = baseball, family = "binomial")
summary(multiModel)
cor(baseball)
cor(baseball$Year, baseball$RA)
cor(baseball$Year, baseball$RankSeason)
cor(baseball$Year, baseball$NumCompetitors)
cor(baseball$RA, baseball$RankSeason)
cor(baseball$RA, baseball$NumCompetitors)
cor(baseball$RankSeason, baseball$NumCompetitors)
summary(glm(WorldSeries ~ Year, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ RA, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ RankSeason, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ NumCompetitors, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ Year + RA, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ Year + RankSeason, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ Year + NumCompetitors, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ RA + RankSeason, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ RA + NumCompetitors, data = baseball, family = "binomial"))
summary(glm(WorldSeries ~ RankSeason + NumCompetitors, data = baseball, family = "binomial"))
