IBM = read.csv('IBMStock.csv')
GE = read.csv('GEStock.csv')
ProcterGamble = read.csv('ProcterGambleStock.csv')
CocaCola = read.csv('CocaColaStock.csv')
Boeing = read.csv('BoeingStock.csv')
#Assignment 1.2
IBM$Date = as.Date(IBM$Date, "%m/%d/%y")
GE$Date = as.Date(GE$Date, "%m/%d/%y")
CocaCola$Date = as.Date(CocaCola$Date, "%m/%d/%y")
ProcterGamble$Date = as.Date(ProcterGamble$Date, "%m/%d/%y")
Boeing$Date = as.Date(Boeing$Date, "%m/%d/%y")
summary(IBM)
summary(CocaCola)
mean(IBM$StockPrice)
min(GE$StockPrice)
max(CocaCola$StockPrice)
median(Boeing$StockPrice)
std(ProcterGamble$StockPrice)
sd(ProcterGamble$StockPrice)
hist(CocaCola,type = "I")
hist(CocaCola)
CocaCola$Date = as.Date(CocaCola$Date, "%m/%d/%y")
CocaCola$Date[1]
hist(CocaCola)
hist(CocaCola$Date, CocaCola$StockPrice)
hist(CocaCola$Date, CocaCola$StockPrice, type = "I")
str(CocaCola)
plot(CocaCola$Date, CocaCola$StockPrice)
plot(CocaCola$Date, CocaCola$StockPrice, type = "I")
plot(CocaCola$Date, CocaCola$StockPrice, type="l")
lines(ProcterGamble$Date, ProcterGamble$StockPrice)
plot(CocaCola$Date, CocaCola$StockPrice, type="l",col="red")
lines(ProcterGamble$Date, ProcterGamble$StockPrice, col = "blue")
abline(v=as.Date(c("2000-03-01")), lwd=2)
abline(v=as.Date(c("1983-01-01")), lwd=2)
abline(v=as.Date(c("1983-12-01")), lwd=2)
#problem 3.1 from now on
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(IBM$Date[301:432], IBM$StockPrice[301:432], type="l", col="blue")
lines(Boeing$Date[301:432], Boeing$StockPrice[301:432], type="l", col="black")
lines(ProcterGamble$Date[301:432], ProcterGamble$StockPrice[301:432], type="l", col="green")
lines(GE$Date[301:432], GE$StockPrice[301:432], type="l", col="cyan")
legend("topright", c("Coca Cola", "IBM", "Boeing", "P&G", "GE"), col = c("red", "blue", "black", "green", "cyan"))
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(IBM$Date[301:432], IBM$StockPrice[301:432], type="l", col="blue")
lines(Boeing$Date[301:432], Boeing$StockPrice[301:432], type="l", col="black")
lines(ProcterGamble$Date[301:432], ProcterGamble$StockPrice[301:432], type="l", col="green")
lines(GE$Date[301:432], GE$StockPrice[301:432], type="l", col="cyan")
abline(v=as.Date(c("2000-03-01")), lwd=2)
plot(CocaCola$Date, CocaCola$StockPrice, type="l", col="red", ylim=c(0,210))
lines(IBM$Date, IBM$StockPrice, type="l", col="blue")
lines(Boeing$Date, Boeing$StockPrice, type="l", col="black")
lines(ProcterGamble$Date, ProcterGamble$StockPrice, type="l", col="green")
lines(GE$Date, GE$StockPrice, type="l", col="cyan")
abline(v=as.Date(c("1995-01-01")), lwd=2)
abline(v=as.Date(c("2006-01-01")), lwd=2)
max(GE$StockPrice)
GE[max(GE$StockPrice) == 156.8437]
GE[,max(GE$StockPrice) == 156.8437]
GE[max(GE$StockPrice) == 156.8437,]
plot(CocaCola$Date[301:432], CocaCola$StockPrice[301:432], type="l", col="red", ylim=c(0,210))
lines(IBM$Date[301:432], IBM$StockPrice[301:432], type="l", col="blue")
lines(Boeing$Date[301:432], Boeing$StockPrice[301:432], type="l", col="black")
lines(ProcterGamble$Date[301:432], ProcterGamble$StockPrice[301:432], type="l", col="green")
lines(GE$Date[301:432], GE$StockPrice[301:432], type="l", col="cyan")
abline(v=as.Date(c("1997-09-01")), lwd=2)
abline(v=as.Date(c("1997-11-01")), lwd=2)
abline(v=as.Date(c("2004-01-01")), lwd=2)
tapply(IBM$StockPrice, months(IBM$Date), mean)
sort(tapply(IBM$StockPrice, months(IBM$Date), mean), decreasing = TRUE)
sort(tapply(GE$StockPrice, months(GE$Date), mean), decreasing = TRUE)
sort(tapply(CocaCola$StockPrice, months(CocaCola$Date), mean), decreasing = TRUE)
#end of assignment

