#chapter 1 assignment 3
#problem 1.1
poll = read.csv('AnonymityPoll.csv')
str(poll)
summary(poll)
smart_phone_users = poll[poll$Smartphone == 1]
smart_phone_users = poll[poll$Smartphone == 1.0]
smart_phone_users = subset(poll, poll$Smartphone == 1.0)
View(smart_phone_users)
1002 - 43 - 487
#problem 1.3
table(poll$Sex, poll$Region)
table(poll$Region, poll$State
)
table(poll$Sex, poll$Region)[1,]
table(poll$Region, poll$State)[1,]
table(poll$Region, poll$State)[1,] > 0
sort(table(poll$Region, poll$State)[1,] > 0)
sort(table(poll$Region, poll$State)[1,] > 0, decreasing = TRUE)
sort(table(poll$Region, poll$State)[3,], decreasing = TRUE)
no_int_no_sp = subset(poll, poll$Smartphone == 0.0 & poll$Internet == 0.0)
View(no_int_no_sp)
yes_int_no_sp = subset(poll, poll$Smartphone == 0.0 & poll$Internet == 1.0)
no_int_yes_sp = subset(poll, poll$Smartphone == 1.0 & poll$Internet == 0.0)
yes_int_yes_sp = subset(poll, poll$Smartphone == 1.0 & poll$Internet == 1.0)
#problem 2.3
#sorry problem 2.2
na_internet = subset(poll, poll$Internet == NA)
View(poll)
na_internet = subset(poll, poll$Smartphone == NA)
na_internet = subset(poll, poll$Smartphone == NA)
na_internet = subset(poll, poll$Smartphone == N/A)
na_internet = subset(poll, poll$Smartphone == NA)
na_smartphone = subset(poll, poll$Smartphone == NA)
View(na_internet)
View(na_internet)
rm(na_internet)
rm(na_smartphone)
summary(poll[is.na(poll$Internet)])
smartphone_na = subset(poll, is.na(poll$Smartphone))
internet_na = subset(poll, is.na(poll$Internet))
limited = subset(poll, poll$Internet == 1.0 | poll$Smartphone == 1.0)
head(limited)
sum(is.na(limited$Sex))
sum(is.na(limited$Age))
sum(is.na(limited$State))
sum(is.na(limited$Regoin))
sum(is.na(limited$Region))
sum(is.na(limited$Conservativeness))
sum(is.na(limited$Info.On.Internet))
sum(is.na(limited$Worry.About.Info))
sum(is.na(limited$Privacy.Importance))
sum(is.na(limited$Anonymity.Possible))
sum(is.na(limited$Tried.Masking.Identity))
sum(is.na(limited$Privacy.Laws.Effective))
sum(is.na(limited$Internet.Use))
sum(is.na(limited$Smartphone))
sum(is.na(limited$Info.On.Internet))
mean(limited$Info.On.Internet)
zero_info_on_internet = subset(limited, limited$Info.On.Internet == 0)
zero_info_on_internet = subset(limited, limited$Info.On.Internet == 11)
sum(limited$Worry.About.Info == 1.0)
sum(limited$Worry.About.Info == 0)
nrow(limited$Worry.About.Info == 1.0)
nrow(limited$Worry.About.Info == 1)
nrow(subset(limited, limited$Worry.About.Info == 1.0))
nrow(subset(limited, limited$Worry.About.Info == 1.0 | limited$Worry.About.Info == 0.0))
386/790
nrow(subset(limited, limited$Anonymity.Possible == 1.0 | limited$Anonymity.Possible == 0.0))
nrow(subset(limited, limited$Anonymity.Possible == 1.0))
278/753
nrow(subset(limited, limited$Tried.Masking.Identity == 1.0))
nrow(subset(limited, limited$Tried.Masking.Identity != NA))
nrow(subset(limited, !is.na(limited$Tried.Masking.Identity)))
nrow(subset(limited, limited$Tried.Masking.Identity == 1.0 | limited$Tried.Masking.Identity == 0.0 ))
128/784
nrow(subset(limited, limited$Privacy.Laws.Effective == 1.0))
nrow(subset(limited, !is.na(limited$Privacy.Laws.Effective)))
186/727
plot(limited$Age)
plot(,limited$Age)
nrow(limited)
plot(range(1,792), limited$Age)
table(limited$Age)
table(limited)
table(limited$Age)
plot(table(limited$Age))
plot(limited$Age, limited$Info.On.Internet)
sort(table(limited$Age, limited$Info.On.Internet))
sort(table(limited$Age, limited$Info.On.Internet), decreasing = TRUE)
table(limited$Age, limited$Info.On.Internet)
limited[table(limited$Age, limited$Info.On.Internet) == 6]
limited[table(limited$Age, limited$Info.On.Internet) == 6,]
jitter(c(1,2,3))
jitter(c(1,2,3))
jitter(c(1,2,3))
plot(jitter(limited$Age), jitter(limited$Info.On.Internet))
plot(jitter(limited$Age), jitter(limited$Info.On.Internet), type = "l")
plot(jitter(limited$Age), jitter(limited$Info.On.Internet))
mean(smart_phone_users$Info.On.Internet)
tapply(limited, limited$Smartphone == 1.0, mean)
smarpthone_limited = subset(limited, limited$Smartphone == 1.0)
no_smarpthone_limited = subset(limited, limited$Smartphone == 0.0)
mean(smarpthone_limited)
mean(smarpthone_limited$Info.On.Internet)
mean(no_smarpthone_limited$Info.On.Internet)
nrow(subset(smartphone_limited, smarpthone_limited$Tried.Masking.Identity == 1.0))
nrow(subset(smartphone_limited, smarpthone_limited$Tried.Masking.Identity == 1.0))
nrow(subset(smarpthone_limited, smarpthone_limited$Tried.Masking.Identity == 1.0))
nrow(subset(smarpthone_limited, !is.na(smarpthone_limited$Tried.Masking.Identity))
)
93/483
nrow(subset(no_smarpthone_limited, !is.na(no_smarpthone_limited$Tried.Masking.Identity)))
nrow(subset(no_smarpthone_limited, no_smarpthone_limited$Tried.Masking.Identity == 1.0))
33/281
#end of assignment
