#chapter 1 assignmnet 4
CPS = read.csv('CPSData.csv')
summary(CPS)
str(CPS)
table(CPS$Industry)
sort(table(CPS$Industry), decreasing = TRUE)
sort(table(CPS$State), decreasing = TRUE)
table(CPS$Citizenship)
116639 + 7073
123712 + 7590
123712/131302
hispanic_dataset = subset(CPS, CPS$Hispanic == 1.0)
table(hispanic_dataset$Race)
table(CPS)
colnames
colnames()
colnames(CPS)
sum(is.na(CPS$PeopleInHousehold))
sum(is.na(CPS$Region))
sum(is.na(CPS$State))
sum(is.na(CPS$MetroAreaCode))
sum(is.na(CPS$Age))
sum(is.na(CPS$Married))
sum(is.na(CPS$Sex))
sum(is.na(CPS$Education))
sum(is.na(CPS$Race))
sum(is.na(CPS$Hispanic))
sum(is.na(CPS$CountryOfBirthCode))
sum(is.na(CPS$Citizenship))
sum(is.na(CPS$EmploymentStatus))
sum(is.na(CPS$Industry))
table(CPS$Region, is.na(CPS$Married))
table(CPS$Age, is.na(CPS$Married))
table(is.na(CPS$Married), CPS$Age)
non_metro_ppl = CPS[is.na(CPS$MetroAreaCode)]
non_metro_ppl = subset(CPS,is.na(CPS$MetroAreaCode)
)
non_metro_ppl = subset(CPS,is.na(CPS$MetroAreaCode))
metro_ppl = subset(CPS,!is.na(CPS$MetroAreaCode))
table(CPS$State, is.na(CPS$MetroAreaCode))
table(CPS$State, is.na(CPS$MetroAreaCode))[,2] == 0
nrow(table(CPS$State, is.na(CPS$MetroAreaCode))[,2] == 0)
count(table(CPS$State, is.na(CPS$MetroAreaCode))[,2] == 0)
sort(table(CPS$State, is.na(CPS$MetroAreaCode))[,2] == 0)
sort(table(CPS$State, is.na(CPS$MetroAreaCode))[,2] == 0, decreasing = TRUE)
sort(table(CPS$State, !is.na(CPS$MetroAreaCode))[,2] == 0, decreasing = TRUE)
table(CPS$State, !is.na(CPS$MetroAreaCode)
)
table(CPS$State, is.na(CPS$MetroAreaCode))
sort(table(CPS$State, !is.na(CPS$MetroAreaCode)), decreasing = TRUE)
sort(table(CPS$State, !is.na(CPS$MetroAreaCode))[,2], decreasing = TRUE)
sort(table(CPS$State, is.na(CPS$MetroAreaCode))[,2], decreasing = TRUE)
sort(table(CPS$Region, is.na(CPS$MetroAreaCode))[,2], decreasing = TRUE)
sort(table(CPS$Region, is.na(CPS$MetroAreaCode)) == TRUE, decreasing = TRUE)
sort(table(CPS$Region, is.na(CPS$MetroAreaCode))[,2], decreasing = TRUE)
sort(table(CPS$Region, is.na(CPS$MetroAreaCode))[,1], decreasing = TRUE)
tapply(is.na(CPS$MetroAreaCode), CPS$State, mean )
sort(tapply(is.na(CPS$MetroAreaCode), CPS$State, mean ), decreasing = TRUE)
MetroAreaMap = read.csv('MetroAreaCodes.csv')
CountryMap = read.csv('CountryCodes.csv')
CPS = merge(CPS, MetroAreaMap, by.x="MetroAreaCode", by.y="Code", all.x=TRUE)
str(CPS)
sum(is.na(CPS$MetroArea))
sort(table(CPS$MetroArea), decreasing = TRUE)
sort(tapply(CPS$Hispanic, CPS$MetroArea, mean), decreasing = TRUE)[1:5]
sort(tapply(CPS$Hispanic, CPS$MetroArea, mean), decreasing = TRUE)[1]
sort(tapply(CPS$Race == "Asian", CPS$MetroArea, mean), decreasing = TRUE)[1]
sort(tapply(CPS$Race == "Asian", CPS$MetroArea, mean), decreasing = TRUE)
tapply(CPS$Race == "Asian", CPS$MetroArea, mean)
tapply(CPS$Race == "Asian", CPS$MetroArea, mean) > 0.2
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean) > 0.2)
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean) > 0.1)
table(tapply(CPS$Race == "Asian", CPS$MetroArea, mean))
sort(tapply(CPS$Education == "No high school diploma", CPS$MetroArea, mean, na.rm = TRUE))
View(CPS)
View(CPS)
View(CountryMap)
View(CountryMap)
CPS2 = merge(CPS, CountryMap, by.x="CountryOfBirthCode", by.y="Code", all.x=TRUE)
View(CPS2)
sum(is.na(CPS2$Country))
View(CPS2)
View(CPS2)
non_US = subset(CPS2, CPS2$Country != "United States")
table(non_US$Country)
sort(table(non_US$Country), decreasing = TRUE)
sort(table(non_US$Country), decreasing = TRUE)[1:5]
NY-NJ-PA = subset(CPS2, CPS2$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA")
NYNJPA = subset(CPS2, CPS2$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA")
NYNJPA = subset(CPS2, CPS2$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA" & !is.na(CPS2$Country))
NYNJPA = subset(CPS2, CPS2$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA")
NYNJPA = subset(CPS2, CPS2$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA" & !is.na(CPS2$Country))
NYNJPA = subset(CPS2, CPS2$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA" & !is.na(CPS2$Country) & CPS2$Country != "United States")
View(NYNJPA)
1668
NYNJPA = subset(CPS2, CPS2$MetroArea == "New York-Northern New Jersey-Long Island, NY-NJ-PA" & !is.na(CPS2$Country))
1668/5404
tapply(CPS2$Country == "India", CPS$MetroArea, mean)
sort(tapply(CPS2$Country == "India", CPS$MetroArea, mean), decreasing = TRUE)[1:5]
sort(tapply(CPS2$Country == "India", CPS2$MetroArea, mean), decreasing = TRUE)[1:5]
sort(tapply(CPS2$Country == "India", CPS2$MetroArea, mean, na.rm = TRUE), decreasing = TRUE)[1:5]
sort(tapply(CPS2$Country == "India", CPS2$MetroArea, mean, na.rm = TRUE), decreasing = TRUE)
sort(tapply(CPS2$Country == "India", CPS2$MetroArea, mean, na.rm = TRUE), decreasing = TRUE)
sort(tapply(CPS2$Country == "Brazil", CPS2$MetroArea, mean, na.rm = TRUE), decreasing = TRUE)
sort(tapply(CPS2$Country == "Somalia", CPS2$MetroArea, mean, na.rm = TRUE), decreasing = TRUE)
