setwd("C:/Thirumal/Learning/edX/The Analytics Edge/Week 05/Assignment")
trials <- read.csv("clinical_trial.csv", stringsAsFactors = FALSE)
str(trials)
library(tm)
library(SnowballC)
corpusTitle <- Corpus(VectorSource(trials$title))
corpusAbstract <- Corpus(VectorSource(trials$abstract))
corpusTitle <- tm_map(corpusTitle, tolower)
corpusAbstract <- tm_map(corpusAbstract, tolower)
corpusTitle <- tm_map(corpusTitle, removePunctuation)
corpusAbstract <- tm_map(corpusAbstract, removePunctuation)
corpusAbstract <- tm_map(corpusAbstract, removeWords, stopwords("english"))
corpusTitle <- tm_map(corpusTitle, removeWords, stopwords("english"))
corpusTitle <- tm_map(corpusTitle, stemDocument)
corpusAbstract <- tm_map(corpusAbstract, stemDocument)
dtmTitle <- DocumentTermMatrix(corpusTitle)
dtmAbstract <- DocumentTermMatrix(corpusAbstract)
dtmTitle <- removeSparseTerms(dtmTitle, 0.95)
dtmAbstract <- removeSparseTerms(dtmAbstract, 0.95)
dtmTitle <- as.data.frame(as.matrix(dtmTitle))
dtmAbstract <- as.data.frame(as.matrix(dtmAbstract))
dtmAbstract <- DocumentTermMatrix(corpusAbstract)
dtmTitle <- DocumentTermMatrix(corpusTitle)
dtmAbstract <- removeSparseTerms(dtmAbstract, 0.95)
dtmTitle <- removeSparseTerms(dtmTitle, 0.95)
dtmTitle <- as.data.frame(as.matrix(dtmTitle))
dtmAbstract <- as.data.frame(as.matrix(dtmAbstract))
colnames(dtmTitle) <- make.names(colnames(dtmTitle))
colnames(dtmAbstract) <- make.names(colnames(dtmAbstract))
str(dtmTitle)
which.max(colSums(dtmAbstract))
colnames(dtmTitle) = paste0("T", colnames(dtmTitle))
colnames(dtmAbstract) = paste0("A", colnames(dtmAbstract))
dtm <- cbind(dtmTitle, dtmAbstract)
str(trials)
dtm$trial <- trials$trial
#splitting the data
library(caTools)
split = sample.split(dtm$trials, SplitRatio=0.7)
split = sample.split(dtm$trial, SplitRatio=0.7)
train = subset(dtm, split == TRUE)
test = subset(dtm, split == FALSE)
table(train$trial)
#accuracy of baseline model
730/(730+572)
library(rpart)
library(rpart.plot)
trialCART = rpart(trial ~ ., data = train, method="class")
prp(trialCART)
predictTrain <- predict(trialCART)
which.max(predictTrain[,2])
max(predictTrain[,2])
View(predictTrain)
max(predictTrain[,1])
predTrain <- predict(trialCART, newdata=train)
max(predTrain[,2])
max(predTrain[,1])
set.seed(144)
split = sample.split(dtm$trial, SplitRatio=0.7)
train = subset(dtm, split == TRUE)
test = subset(dtm, split == FALSE)
trialCART = rpart(trial ~ ., data = train, method="class")
predictTrain <- predict(trialCART)
max(predTrain[,1])
max(predTrain[,2])
predictTest <- predict(trialCART, newdata = test)
max(predictTest)
max(predTrain)
set.seed(144)
spl = sample.split(dtm$trial, 0.7)
train = subset(dtm, spl == TRUE)
test = subset(dtm, spl == FALSE)
trialCART <- rpart(trial ~ ., data=train, method="class")
prp(trialCART)
predTrain <- predict(trialCART)
max(predTrain[,2])
rm(predictTest)
rm(predictTrain)
predTest <- predict(trialCART, newdata = test)
max(predTest[,2])
table(dtm$trial, predictTrain[,2] > 0.5)
table(dtm$trial, predTrain[,2] > 0.5)
table(train$trial, predictTrain[,2] > 0.5)
table(train$trial, predTrain[,2] > 0.5)
(631+441)/(631+441+99+131) #Accuracy of training set
#sensitivity
631/(631+131)
#specificity
441/(441+99)
table(train$trial, predictTrain[,2] >= 0.5)
table(train$trial, predTrain[,2] >= 0.5)
#sensistvity = tp/(tp+fn)
441/(441+131)
#specificity = tn/(tn+fp)
631/(631+99)
table(test$trial, predTest[,2] > 0.5)
(261+162)/(558)
library(ROCR)
ROCRpred = prediction(predTest, test$trial)
??prediction
library(caret)
ROCRpred = prediction(predTest, test$trial)
library(ROCR)
library(gplots)
library(gdata)
install.packages("gdata")
library(gplots)
library(ROCR)
ROCRpred = prediction(predTest, test$trial)
ROCRpred = prediction(predTest[,2], test$trial)
as.numeric(performance(ROCRpred, "auc")@y.values)
table(test$trial, predTest[,2] > 0.5)
table(test$trial, predTest[,2] > 0.9)
table(test$trial, predTest[,2] > 0.7)
table(test$trial, predTest[,2] > 0.3)
table(test$trial, predTest[,2] > 0.2)
table(test$trial, predTest[,2] > 0.3)
table(test$trial, predTest[,2] > 0.25)
table(test$trial, predTest[,2] > 0.17)
table(test$trial, predTest[,2] > 0.15)
table(test$trial, predTest[,2] > 0.13)
