emails = read.csv("emails.csv", stringsAsFactors=FALSE)
corpus = Corpus(VectorSource(emails$text))
corpus = tm_map(corpus, tolower)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, stopwords("english"))
corpus = tm_map(corpus, stemDocument)
dtm = DocumentTermMatrix(corpus)
spdtm = removeSparseTerms(dtm, 0.95)
emailsSparse = as.data.frame(as.matrix(spdtm))
colnames(emailsSparse) <- make.names(colnames(emailsSparse))
set.seed(123)
spl = sample.split(emailsSparse$spam, SplitRatio=0.7)
train = subset(emailsSparse, spl == TRUE)
test = subset(emailsSparse, spl == FALSE)
emailsSparse$spam <- emails$spam
set.seed(123)
spl = sample.split(emailsSparse$spam, SplitRatio=0.7)
train = subset(emailsSparse, spl == TRUE)
test = subset(emailsSparse, spl == FALSE)
wordCount = rowSums(as.matrix(dtm))
hist(wordCount)
hist(log(wordCount))
rm(train)
rm(test)
emailsSparse$logWordCount <- log(wordCount)
boxplot(emailsSparse$logWordCount)
boxplot(emailsSparse[c("logWordCount","spam")])
boxplot(logWordCount ~ spam, data = emailsSpasre)
boxplot(logWordCount ~ spam, data = emailsSparse)
set.seed(123)
spl = sample.split(emailsSparse$spam, SplitRatio=0.7)
emailsSparse$logWordCount <- NULL
train = subset(emailsSparse, spl == TRUE)
test = subset(emailsSparse, spl == FALSE)
emailsSparse$logWordCount <- log(wordCount)
train2 = subset(emailsSparse, spl == TRUE)
test2 = subset(emailsSparse, spl == FALSE)
spam2CART = rpart(spam ~ ., data=train2, method ="class")
prp(spam2CART)
pred2CART = predict(spam2CART, type="response")
pred2CART = predict(spam2CART, type="prob")
pred2CART = predict(spam2CART, type="prob")[,2]
pred2CART = predict(spam2CART, newdata = test2, type="prob")[,2]
table(test2$spam, pred2CART > 0.5)
(1214+384)/1718
ROCRCART2pred = prediction(pred2CART, test2$spam)
as.numeric(performance(ROCRCART2pred)@y.values)
as.numeric(performance(ROCRCART2pred, "perf")@y.values)
as.numeric(performance(ROCRCART2pred, "auc")@y.values)
spam2RF = randomForest(spam ~ ., data = train2, method="class")
spam2RF = randomForest(spam ~ ., data = train2)
set.seed(123)
train2$spam <- as.factor(train2$spam)
test2$spam <- as.factor(test2$spam)
test$spam <- as.factor(test$spam)
train$spam <- as.factor(train$spam)
emailsSparse$spam <- as.factor(emailsSparse$spam)
set.seed(123)
spam2RF = randomForest(spam ~ ., data = train2)
pred2RF <- predict(spam2RF, newdata = test2)
fix(pred2RF)
pred2RF <- predict(spam2RF, newdata = test2, type = "response")
fix(pred2RF)
pred2RF <- predict(spam2RF, newdata = test2, type = "prob")
pred2RF <- predict(spam2RF, newdata = test2, type = "prob")[,2]
table(test$spam, pred2RF)
table(test$spam, pred2RF > 0.5)
(1298+382)/1718
ROCR2RFPred = prediction(pred2RF, test$spam)
as.numeric(performance(ROCR2RFPred, "auc")@y.values)
install.packages("RTextTools")
library(RTextTools)
dtm2gram = create_matrix(as.character(corpus), ngramLength=2)
str(dtm2gram)
spdtm2gram <- removeSparseTerms(dtm2gram, 0.95)
str(spdtm2gram)
str(spdtm)
emailsSparse2gram = as.data.frame(as.matrix(spdtm2gram))
colnames(emailsSparse2gram) <- make.names(colnames(emailsSparse2gram))
emailsCombined = cbind(emailsSparse, emailsCombined)
emailsCombined = cbind(emailsSparse, emailsSparse2gram)
trainCombined = subset(emailsCombined, spl == TRUE)
testCombined = subset(emailsCombined, spl == FALSE)
spamCARTcombined = rpart(spam ~ ., data = trainCombined, method = "class")
spamRFcombined = randomForest(spam ~ ., data = trainCombined)
prp(spamCARTcombined, varlen=0)
pred3CART = predict(spamCARTcombined, newdata = testCombined)
pred3CART = predict(spamCARTcombined, newdata = testCombined)[,2]
table(testCombined$spam, pred3CART > 0.5)
(1233+371)/1718
rocrCART = prediction(pred3CART, testCombined$spam)
as.numeric(performance(rocrCART, "auc")@y.values)
pred3RF = predict(spamRFcombined, newdata = testCombined)[,2]
pred3RF = predict(spamRFcombined, newdata = testCombined, type = "prob")[,2]
table(testCombined$spam, pred3RF > 0.5)
(1297+385)/1718
rocrRF = prediction(pred3RF, testCombined$spam)
as.numeric(performance(rocrRF, "auc")@y.values)
