setwd("C:/Thirumal/Learning/edX/The Analytics Edge/Week 05/Assignment")
emails = read.csv("emails.csv", stringsAsFactors=FALSE)
str(emails)
table(emails$spam)
max(nchar(emails$text))
which.min(nchar(emails$text))
corpus = Corpus(VectorSource(emails$text))
corpus = tm_map(corpus, tolower)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, stopwords("english"))
corpus = tm_map(corpus, stemDocument)
dtm = DocumentTermMatrix(corpus)
str(dtm)
spdtm = removeSparseTerms(dtm, 0.95)
str(spdtm)
emailsSparse = as.data.frame(as.matrix(spdtm))
colnames(emailsSparse) <- make.names(colnames(emailsSparse))
which.max(colSums(emailsSparse))
emailsSparse$spam <- emails$spam
tempHam <- subset(emailsSparse, spam == 0)
tempSpam <- subset(emailsSparse, spam == 1)
hamcolsums <- colSums(tempHam)
spamcolsums <- colSums(tempSpam)
hamcolsums$spam <- NULL
tempHam$spam <- NULL
tempSpam$spam <- NULL
hamcolsums <- colSums(tempHam)
spamcolsums <- colSums(tempSpam)
sum(hamcolsums > 5000)
sum(spamcolsums > 1000)
tempSpam[spamcolsums > 1000]
colnames(tempSpam)[spamcolsums > 1000]
colnames(tempHam)[hamcolsums > 5000]
emailsSparse$spam = as.factor(emailsSparse$spam)
set.seed(123)
spl = sample.split(emailsSparse$spam, SplitRatio=0.7)
train = subset(emailsSparse, spl == TRUE)
test = subset(emailsSparse, spl == FALSE)
rm(tempHam)
rm(tempSpam)
spamLog = glm(spam ~ ., data = train, family="binomial")
spamCART = rpart(spam ~ ., data = train, method = "class")
set.seed(123)
library(randomForest)
set.seed(123)
spamRF = randomForest(spam ~ ., data=train)
predLog = predict(spamLog)[,2]
predLog = predict(spamLog)
str(predLog)
predLog = predict(spamLog, type="response")[,2]
rm(predLog)
predLog = predict(spamLog)
summarypredLog
summary(predLog)
fix(predLog)
summary(spamLog)
predLog <- predict(spamLog)
predLog
spamLog = glm(spam ~ ., data = train, family="binomial")
predLog <- predict(spamLog, data=train)
predLog
predLog <- predict(spamLog, type="prob")
str(train$spam)
predCART <- predict(spamCART, type="response")
predCART <- predict(spamCART, type="prob")
predRF <- predict(spamRF, type="prob")
library(stats)
predLog <- predict(spamLog, type="prob")
predLog <- predict(spamLog, type="response")
str(predLog)
fix(predLog)
table(predLog)
sum(predLog < 0.00001)
sum(predLog > 0.99999)
sum(predLog > 0.00001 & predLog < 0.99999)
3046+954+10
summary(spamLog)
prp(spamCART)
table(train$spam, predLog > 0.5)
(3052+954)/(3052+954+4)
ROCRLogpred = prediction(predLog, train$spam)
as.numeric(performance(ROCRLogpred, "auc")@y.values)
table(train$table, predCART[,2] > 0.5)
table(train$spam, predCART[,2] > 0.5)
(2885+894)/4010
ROCRCARTPred = prediction(predCART[,2], train$spam)
as.numeric(performance(ROCRCARTPred, "auc")@y.values)
table(train$spam, predRF[,2] > 0.5)
(3013+914)/4010
ROCRRFPred = prediction(predRF[,2], train$spam)
as.numeric(performance(ROCRRFPred, "auc")@y.values)
predTLog <- predict(spamLog, newdata=test)
table(test$spam, predTLog > 0.5)
(1258+376)/1718
ROCRLogpred = prediction(predTLog, test$spam)
as.numeric(performance(ROCRLogpred, "auc")@y.values)
predTCART <- predict(spamCART, newdata=test)
ROCRCARTPred = prediction(predTCART[,2], test$spam)
as.numeric(performance(ROCRCARTPred, "auc")@y.values)
table(test$spam, predTCART[,2] > 0.5)
(1228+386)/1718
predTRF <- predict(spamRF, newdata = test)
ROCRRFPred = prediction(predTRF[,2], test$spam)
library(stats)
predTRF <- predict(spamRF, newdata = test)
fix(predTLog)
predTRF <- predict(spamRF, newdata = test, type = "response")
rm(predTRF)
rm(spamRF)
set.seed(123)
spamRF = randomForest(spam ~ ., data=train)
predTRF <- predict(spamRF, newdata=test, type="prob")
table(test$spam, predTRF[,2] > 0.5)
(1290+385)/1718
ROCRRFPred = prediction(predTRF[,2], test$spam)
as.numeric(performance(ROCRRFPred, "auc")@y.values)
