census = read.csv("census.csv")
set.seed(2000)
library(caTools)
set.seed(2000)
split = sample.split(census$over50k, SplitRatio=0.6)
test = subset(census, split == FALSE)
train = subset(census, split == TRUE)
linCensus = lm(over50k ~ ., data = train)
logCensus = glm(over50k ~ ., data = train, family = "binomial")
summary(logCensus)
table(test$over50k)
9713/12791
PredLogCensus = predict(logCensus, newdata = test, type="response")
fix(PredLogCensus)
talbe(test$over50k, PredLogCensus >= 0.5)
table(test$over50k, PredLogCensus >= 0.5)
(9051+1888)/12791
library(ROCR)
ROCRpred = prediction(PredLogCensus, test$over50k)
ROCRperf = performance(ROCRpred, "tpr", "fpr")
as.numeric(performance(ROCRpred, "auc")@y.values)
censusTree = rpart(over50k ~ ., data = train, type = "class")
censusTree = rpart(over50k ~ ., data = train, method = "class")
prp(censusTree)
predCensusTree = predict(censusTree, newdata = test, type = "response")
predCensusTree = predict(censusTree, newdata = test)
predCensusTree = predict(censusTree, newdata = test, type = "class")
table(test$over50k, predCensusTree)
(9243+1596)/12791
fix(predCensusTree)
predROCTree = prediction(predCensusTree, test$over50k)
fix(PredLogCensus)
predCensusTree = predict(censusTree, newdata = test, type = "prob")
table(test$over50k, predCensusTree > 0.5)
predCensusTree = predict(censusTree, newdata = test, type = "prob")
table(test$over50k, predCensusTree[,2] > 0.5)
predROCTree = prediction(predCensusTree[,2], test$over50k)
perfROCTree = performance(predROCTree, "tpr", "fpr")
plot(perfROCTree)
as.numeric(performance(pred, "auc")@y.values)
as.numeric(performance(predROCTree, "auc")@y.values)
set.seed(1)
trainSmall = train[sample(nrow(train), 2000), ]
censusrf = randomForest( over50k ~ . , data = trainSmall)
str(trainSmall)
censusrf = randomForest( over50k ~ . - nativeCountry, data = trainSmall)
censusrf = randomForest( over50k ~ . - nativecountry, data = trainSmall)
set.seed(1)
censusrf = randomForest( over50k ~ . - nativecountry, data = trainSmall)
predrf = predict(censusrf, newdata = test)
table(test$over50k, predrf)
(8861+2038)/12791
vu = varUsed(censusrf, count=TRUE)
vusorted = sort(vu, decreasing = FALSE, index.return = TRUE)
vusorted
dotchart(vusorted$x, names(censusrf$forest$xlevels[vusorted$ix]))
varImpPlot(censusrf)
set.seed(2)
fitControl = trainControl(method = "cv", number = 10)
cartGrid = expand.grid( .cp = seq(0.002,0.1,0.002))
train(Reverseover50k ~ . - nativecountry, data = trainSmall, method = "rpart", trControl = fitControl, tuneGrid = cartGrid )
train(over50k ~ . - nativecountry, data = trainSmall, method = "rpart", trControl = fitControl, tuneGrid = cartGrid )
set.seed(2)
train(over50k ~ . - , data = train, method = "rpart", trControl = fitControl, tuneGrid = cartGrid )
train(over50k ~ . , data = train, method = "rpart", trControl = fitControl, tuneGrid = cartGrid )
cartCV = rpart(over50k ~ ., data = train)
cartCV = rpart(over50k ~ ., data = train, cp = 0.002)
predCV = predict(cartCV, newdata = test, type = "class")
table(test$over50k, predCV)
(9178+1838)/12791
prp(cartCV)
cartCV
############DONE###################
