setwd("C:/Thirumal/Learning/edX/The Analytics Edge/Week 04/Assignment")
letters = read.csv("letters_ABPR.csv")
letters$isB = as.factor(letters$letter == "B")
library(caTools)
set.seed(1000)
split = sample.split(letters, SplitRatio=0.5)
fix(split)
set.seed(1000)
split = sample.split(letters$isB, SplitRatio=0.5)
mean(letters$isB)
table(letters$isB)
2350/(2350+766)
CARTb = rpart(isB ~ . - letter, data=train, method="class")
train = subset(letters, split == TRUE)
test = subset(letters, split == FALSE)
CARTb = rpart(isB ~ . - letter, data=train, method="class")
predictCARTb = predict(CARTb, newdata = test type="class")
predictCARTb = predict(CARTb, newdata = test, type="class")
table(train$isB, predictCARTb)
(880+102)/(880+102+281+295)
table(test$isB, predictCARTb)
(1118+340)/(1118+340+57+43)
library(randomForests)
library(randomForest)
set.seed(1000)
lettersForest = randomForest(isB ~ . - letter, data=train, method="class")
set.seed(1000)
lettersForest = randomForest(isB ~ . - letter, data=train)
str(train)
set.seed(1000)
lettersForest = randomForest(isB ~ . - letter, data=train)
predictForest = predict(lettersForest, newdata=test, type="class")
predictForest = predict(lettersForest, newdata=test)
table(test$isB, predictForest)
(1165+374)/(1165+374+19)
letters$letter = as.factor( letters$letter )
set.seed(2000)
split = sample.split(letters$letter, SplitRatio=0.5)
train = subset(letters, split == TRUE)
test = subset(letters, split == FALSE)
table(letters$letter)
789/(789+766+803+758)
table(test$letter)
401/(395+383+401+379)
test$isB <- NULL
train$isB <- NULL
str(train)
letterCART2 = rpart(letter ~ ., data = train, method = "class")
predCART2 = predict(letterCART2, type = "response")
predCART2 = predict(letterCART2, newdata = test, type = "response")
predCART2 = predict(letterCART2, newdata = test)
View(predCART2)
predCART2 = predict(letterCART2, newdata = test, type="class")
View(train)
fix(predCART2)
table(test$letter, predCART2)
(348+318+363+340)/1558
letterForest2 = randomForest(letter ~ ., data=train)
letterPred2 = predict(letterForest2, newdata = test)
table(test$letter, letterPred2)
(390+380+393+369)/1558
#############DONE##########################
