data(state)
statedata = data.frame(state.x77)
str(statedata)
linState = lm(Life.Exp ~ ., data = statedata)
summary(linState)
linStateResp = predict(linState)
sse = sum((linStateResp - statedata$Life.Exp)^2)
sse
linState2 = lm(Life.Exp ~ Population + Murder + Frost + HS.Grad, data = statedata)
linStateResp2 = predict(linState2)
sse = sum((linStateResp2 - statedata$Life.Exp)^2)
summary(linState2)
sse
cor(statedata)
stateTree = rpart(Life.Exp ~ ., data=statedata)
stateTree
prp(stateTree)
stateTreeResp = predict(stateTree)
sum((stateTreeResp - statedata$Life.Exp)^2)
stateTree2 = rpart(Life.Exp ~ ., data=statedata, control=rpart.control(minbucket=5))
prp(stateTree)
prp(stateTree2)
prp(rpart(Life.Exp ~ ., data=statedata, control=rpart.control(minbucket=5)))
prp(rpart(Life.Exp ~ ., data=statedata, control=rpart.control(minbucket=20)))
prp(rpart(Life.Exp ~ ., data=statedata, control=rpart.control(minbucket=1)))
stateTreeResp2 = predict(stateTree2)
sum((stateTreeResp2 - statedata$Life.Exp)^2)
stateTree3 = rpart(Life.Exp ~ Area, data=statedata, control=rpart.control(minbucket=5))
stateTreeResp3 = predict(stateTree3)
sum((stateTreeResp3 - statedata$Life.Exp)^2)
stateTree3 = rpart(Life.Exp ~ Area, data=statedata, control=rpart.control(minbucket=1))
stateTreeResp3 = predict(stateTree3)
sum((stateTreeResp3 - statedata$Life.Exp)^2)
library(caret)
library(e1071)
set.seed(111)
fitControl = trainControl(method="cv", number=10)
cartGrid = expand.grid(.cp=(1:50)*0.01)
train(Life.Exp ~ ., data=Train, method="rpart", trControl=fitControl, tuneGrid = cartGrid)
train(Life.Exp ~ ., data=statedata, method="rpart", trControl=fitControl, tuneGrid = cartGrid)
stateTree5 = rpart(Life.Exp ~ ., data=statedata, control=rpart.control(.cp=0.12))
prp(stateTree5)
stateTreeResp5 = predict(stateTree5)
sum((stateTreeResp5 - statedata$Life.Exp)^2)
stateTreeResp5 = predict(stateTree5, type="response")
stateTreeResp5 = predict(stateTree5)
sum((stateTreeResp5 - statedata$Life.Exp)^2)
fix(stateTreeResp5)
stateTreeResp5
stateTreeResp4
stateTreeResp3
prp(stateTree5)
set.seed(111)
train(Life.Exp ~ ., data=statedata, method="rpart", trControl=fitControl, tuneGrid = cartGrid)
stateTree5 = rpart(Life.Exp ~ ., data=statedata, control=rpart.control(.cp=0.12))
pred5 = predict(stateTree5)
sum((pred5 - statedata$Life.Exp)^2)
set.seed(111)
train(Life.Exp ~ Area, data=statedata, method="rpart", trControl=fitControl, tuneGrid = cartGrid)
stateTree6 = rpart(Life.Exp ~ Area, data=statedata, control=rpart.control(.cp=0.02))
prp(stateTree6)
CARTmodel5 = rpart(Life.Exp ~ ., data=statedata, cp=0.12)
pred5 = predict(CARTmodel5)
sum((pred5 - statedata$Life.Exp)^2)
stateTree6 = rpart(Life.Exp ~ Area, data=statedata, cp = 0.02)
pred6 = predict(stateTree6)
sum((pred6 - statedata$Life.Exp)^2)
###############DONE###################
