setwd("C:/Thirumal/Learning/edX/The Analytics Edge/Week 04/Assignment")
stevens = read.csv("stevens.csv")
str(stevens)
library(caTools)
set.seed(3000)
split = sample.split(stevens$Reverse, SplitRatio=0.7)
Train = subset(stevens, split == TRUE)
Test = subset(stevens, split == FALSE)
library(rpart)
library(rpart.plot)
StevensTree = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method = "class", control=rpart.control(minbucket=25))
str(StevensTree)
summary(StevensTree)
prp(StevensTree)
PredictCART = predict(StevensTree, newdata = Test, type = "class")
table(Test$Reverse, PredictCART)
(44+71)/(44+71+22+36)
library(ROCR)
PredictROC = predict(StevensTree, newdata = test)
PredictROC = predict(StevensTree, newdata = Test)
pred = prediction(PredictROC[,2], Test$Reverse)
perf = performance(pred, "tpr", "fpr")
plot(perf)
auc = as.numeric(performance(pred, "auc")@y.values)
auc
StevensTree5 = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method = "class", control=rpart.control(minbucket=5))
StevensTree100 = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method = "class", control=rpart.control(minbucket=100))
summary(StevensTree5)
plot(StevensTree5)
str(StevensTree)
fix(StevensTree5)
plot(StevensTree100)
plot(StevensTree100)
summary(StevensTree100)
#random forests
install.packages("randomForest")
library(randomForest)
StevensForest = randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, nodesize = 25, ntree = 200)
Train$Reverse = as.factor(Train$Reverse)
Test$Reverse = as.factor(Test$Reverse)
StevensForest = randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, nodesize = 25, ntree = 200)
predictForest = predict(StevensForest,  newdata = Test)
table(Test$Reverse, predictForest)
(41 +75)/(41+36+18+75)
set.seed(100)
StevensForest2 = randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, nodesize = 25, ntree = 200)
predictForest2 = predict(StevensForest,  newdata = Test)
table(Test$Reverse, predictForest2)
set.seed(200)
StevensForest3 = randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, nodesize = 25, ntree = 200)
predictForest2 = predict(StevensForest2,  newdata = Test)
table(Test$Reverse, predictForest2)
(43+74)/(43+34+19+74)
predictForest3 = predict(StevensForest3,  newdata = Test)
table(Test$Reverse, predictForest3)
(45+76)/(45+32+17+76)
#cross validation by many folds
install.packages("caret")
library(caret)
install.packages("e1071")
library(e1071)
fitControl = trainControl(method="cv", number=10)
cartGrid = expand.grid(.cp=(1:50)*0.01)
train(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="rpart", trControl=fitControl, tuneGrid = cartGrid)
StevensTreeCV = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="class", control=rpart.control(.cp=0.19))
summary(StevensTreeCV)
set.seed(3000)
train(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="rpart", trControl=fitControl, tuneGrid = cartGrid)
StevensTreeCV = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="class", control=rpart.control(.cp=0.19))
PredictCV = predict(StevensTreeCV, newdata=Test, type = "class")
table(Test$Reverse, PredictCV)
(43+65)/(43+34+28+65)
set.seed(3000)
fitControl = trainControl(method="cv", number=10)
train(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="rpart", trControl=fitControl, tuneGrid = cartGrid)
StevensTreeCV = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="class", control=rpart.control(.cp=0.19))
StevensTreeCV = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="class", control=rpart.control(cp=0.19))
PredictCV = predict(StevensTreeCV, newdata=Test, type = "class")
table(Test$Reverse, PredictCV)
(59+64)/(59+18+29+64)
prp(StevensTreeCV)
