tweets = read.csv("tweets.csv")
tweets = read.csv("tweets.csv", stringsAsFactors=FALSE)
library(tm)
library(SnowballC)
corpus = Corpus(VectorSource(tweets$Tweet))
corpus = tm_map(corpus, tolower)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, stopwords("english"))
frequencies = DocumentTermMatrix(corpus)
allTweets = as.data.frame(as.matrix(frequencies))
dim(allTweets)
install.packages("wordcloud")
library(wordcloud)
?wordcloud
View(allTweets)
wordcloud(colnames(allTweets), colSums(allTweets))
wordcloud(colnames(allTweets), colSums(allTweets), scale=c(2, 0.25))
corpus = Corpus(VectorSource(tweets$Tweet))
corpus = tm_map(corpus, tolower)
corpus = tm_map(corpus, removePunctuation)
corpus = tm_map(corpus, removeWords, c("apple", stopwords("english")))
frequencies = DocumentTermMatrix(corpus)
allTweets = as.data.frame(frequencies)
allTweets = as.data.frame(as.matrix(frequencies))
wordcloud(colnames(allTweets), colSums(allTweets), scale=c(2, 0.25))
wordcloud(colnames(allTweets), colSums(allTweets))
wordcloud(colnames(allTweets), colSums(allTweets), scale=c(2, 0.25))
wordcloud(colnames(allTweets), colSums(allTweets), scale=c(2, 0.25), random.order=FALSE)
?wordcloud
wordcloud(colnames(allTweets), colSums(allTweets), scale=c(2, 0.25), rot.per=0.9)
display.brewer.all()
brewer.pal(9, "Blues")
brewer.pal(9, "Blues")[c(-5, -6, -7, -8, -9)]
brewer.pal(9, "Blues")[c(-1, -2, -3, -4)]