##########assignment 1###############
dailykos = read.csv("dailykos.csv")
str(dailykos)
str(dailykos[2:])
str(dailykos[2:1546])
distances = dist(dailykos[2:1546], method = "euclidean")
clusterKos = hclust(distances, method ="ward")
plot(clusterKos)
clusterGroups = cutree(clusterKos, k=7)
tapply(dailyKos$Document, clusterGroups, mean)
tapply(dailykos$Document, clusterGroups, mean)
sum(clusterGroups == 3)
table(clusterGroups)
max(table(clusterGroups))
which.max(table(clusterGroups))
which.min(table(clusterGroups))
HierCluster1 = subset(dailyKos, clusterGroups == 1)
HierCluster1 = subset(dailykos, clusterGroups == 1)
HierCluster2 = subset(dailykos, clusterGroups == 2)
HierCluster3 = subset(dailykos, clusterGroups == 3)
HierCluster4 = subset(dailykos, clusterGroups == 4)
HierCluster4 = subset(dailykos, clusterGroups == 5)
HierCluster4 = subset(dailykos, clusterGroups == 4)
HierCluster5 = subset(dailykos, clusterGroups == 5)
HierCluster6 = subset(dailykos, clusterGroups == 6)
HierCluster7 = subset(dailykos, clusterGroups == 7)
tail(sort(colMeans(HierCluster1[-1])))
tail(sort(colMeans(HierCluster2[-1])))
tail(sort(colMeans(HierCluster3[-1])))
tail(sort(colMeans(HierCluster4[-1])))
tail(sort(colMeans(HierCluster5[-1])))
tail(sort(colMeans(HierCluster6[-1])))
tail(sort(colMeans(HierCluster7[-1])))
###performing kmeans now
kosMatrix = as.matrix(dailykos[2:1546])
kosVector = as.vector(kosMatrix)
k=7
set.seed(1000)
KMC = kmeans(kosVector, centers=k)
kosCluster2 = KMC$cluster
str(kosCluster2)
table(kosCluster2)
which.max(table(kosCluster2))
which.min(table(kosCluster2))
rm(kosVector)
rm(kosMatrix)
KMC = kmeans(dailykos[2:1546], centers=k)
set.seed(1000)
KMC = kmeans(dailykos[2:1546], centers=k)
str(KMC$cluster)
table(KMC$cluster)
kosCluster2 = KMC$cluster
kCluster1 = subset(dailykos, kosCluster2 == 1)
kCluster2 = subset(dailykos, kosCluster2 == 2)
kCluster3 = subset(dailykos, kosCluster2 == 3)
kCluster4 = subset(dailykos, kosCluster2 == 4)
kCluster5 = subset(dailykos, kosCluster2 == 5)
kCluster6 = subset(dailykos, kosCluster2 == 6)
kCluster7 = subset(dailykos, kosCluster2 == 7)
which.min(table(kosCluster2))
which.max(table(kosCluster2))
tail(sort(colMeans(kCluster1[-1])))
tail(sort(colMeans(kCluster2[-1])))
tail(sort(colMeans(kCluster3[-1])))
tail(sort(colMeans(kCluster4[-1])))
tail(sort(colMeans(kCluster5[-1])))
tail(sort(colMeans(kCluster6[-1])))
tail(sort(colMeans(kCluster7[-1])))
table(kosCluster2)
table(clusterGroups)
table(kosCluster2, clusterGroups)
