setwd("C:/Thirumal/Learning/edX/The Analytics Edge/Week 06/Assignment")
airlines = read.csv("AirlinesCluster.csv")
str(airlines)
colMeans(airlines)
library(caret)
preproc = preProcess(airlines)
airlinesNorm = predict(preproc, airlines)
colMeans(airlines)
colMeans(airlinesNorm)
summary(airlinesNorm)
min(summary(airlinesNorm))
distances = dist(airlinesNorm, method="euclidean")
clustAirlines = hclust(distances, method="ward")
plot(clustAirlines)
clusterGroups = cutree(clustAirlines, k=5)
table(clusterGroups)
tapply(airlines$Balance, clusterGroups, mean)
tapply(airlines$QualMiles, clusterGroups, mean)
tapply(airlines$BonusMiles, clusterGroups, mean)
tapply(airlines$BonusTrans, clusterGroups, mean)
tapply(airlines$FlightMiles, clusterGroups, mean)
tapply(airlines$FlightTrans, clusterGroups, mean)
tapply(airlines$DaysSinceEnroll, clusterGroups, mean)
which.max(tapply(airlines$DaysSinceEnroll, clusterGroups, mean))
which.max(tapply(airlines$FlightTrans, clusterGroups, mean))
which.max(tapply(airlines$FlightMiles, clusterGroups, mean))
which.max(tapply(airlines$BonusTrans, clusterGroups, mean))
which.max(tapply(airlines$BonusMiles, clusterGroups, mean))
which.max(tapply(airlines$QualMiles, clusterGroups, mean))
which.max(tapply(airlines$Balance, clusterGroups, mean))
set.seed(88)
k=5
set.seed(88)
KMC = kmeans(airlinesNorm, centers = k, iter.max=1000)
kClusters = KMC$cluster
table(kClusters)
sum(kclusters > 1000)
sum(kClusters > 1000)
sum(table(kClusters) > 1000)
table(kClusters, clusterGroups)
table(kClusters)
table(clusterGroups)
