setwd("C:/Thirumal/Learning/edX/The Analytics Edge/Week 06/Assignment")
claims = read.csv("reimbursement.csv")
str(claims)
colnames(claims)
rmeans <- rowMeans(claims[c("alzheimers","arthritis","cancer","copd","depression","diabetes","heart.failure", "ihd","kidney","osteoporosis","stroke")])
sum(rowMeans > 0)
sum(rmeans > 0)
table(rmeans)
rsums <- rowSums(claims[c("alzheimers","arthritis","cancer","copd","depression","diabetes","heart.failure", "ihd","kidney","osteoporosis","stroke")])
table(rsums)
458005-177578
sum(table(rsums))
NumConditions = rowSums(claims[,2:12])
mean(NumConditions > 0)
280427/458005
cor(claims[,2:12], claims[,2:12])
sort(cor(claims[,2:12], claims[,2:12]), decreasing=TRUE)
hist(claims$reimbursement2009)
claims$reimbursement2008 = log(claims$reimbursement2008+1)
claims$reimbursement2009 = log(claims$reimbursement2009+1)
log(0)
hist(claims$reimbursement2009)
sum(claims$reimbursement2009 == 0)
90498/458005
set.seed(144)
spl = sample(1:nrow(claims), size=0.7*nrow(claims))
train = claims[spl,]
test = claims[-spl,]
lm.claims = lm(reimbursement2009 ~ ., data = train)
summary(lm.claims)
lm.testPred = predict(lm.claims, newdata = test)
sqrt(sum((test$reimbursement2009 - lm.testPred)^2))
sqrt(mean((test$reimbursement2009 - lm.testPred)^2))
sum(test$reimbursement2009 == 0)
rnow(test)
nrow(test)
27177/137402
sqrt(mean((train$reimbursement2009 - mean(train$reimbursement2009))^2))
sqrt(mean((test$reimbursement2009 - test$reimbursement2008)^2))
train.limited = train
train.limited$reimbursement2009 = NULL
test.limited = test
test.limited$reimbursement2009 = NULL
library(caret)
preproc = preProcess(train.limited)
train.norm = predict(preproc, train.limited)
test.norm = predict(preproc, test.limited)
summary(train.norm)
mean(train.norm$arthritis)
mean(test.norm$arthritis)
plot(train.norm$arthritis)
hist(train.norm$arthritis)
hist(test.norm$arthritis)
set.seed(144)
k = 3
set.seed(144)
km <- kmeans(train.norm, centers = k)
kcluster1 <- subset(train, km$cluster == 1)
kcluster2 <- subset(train, km$cluster == 2)
kcluster3 <- subset(train, km$cluster == 3)
summary(kcluster1)
summary(claims)
km$centers
library(flexclust)
km.kcca = as.kcca(km, train.norm)
cluster.train = predict(km.kcca)
cluster.test = predict(km.kcca, newdata=test.norm)
table(cluster.test)
train1 <- subset(train, cluster.train == 1)
train2 <- subset(train, cluster.train == 2)
train3 <- subset(train, cluster.train == 3)
test1 <- subset(train, cluster.test == 1)
test1 <- subset(test, cluster.test == 1)
test2 <- subset(test, cluster.test == 2)
test3 <- subset(test, cluster.test == 3)
tapply(train$reimbursement2009, cluster.train, mean)
lm1 = lm(reimbursement2009 ~ ., data = train1)
lm2 = lm(reimbursement2009 ~ ., data = train2)
lm3 = lm(reimbursement2009 ~ ., data = train3)
summary(lm1)
summary(lm2)
summary(lm3)
set.seed(144)
km = kmeans(train.norm, centers=3)
library(flexclust)
km.kcca = as.kcca(km, train.norm)
cluster.train = predict(km.kcca)
cluster.test = predict(km.kcca, newdata=test.norm)
train1 = subset(train, cluster.train == 1)
train2 = subset(train, cluster.train == 2)
train3 = subset(train, cluster.train == 3)
test1 = subset(test, cluster.test == 1)
test2 = subset(test, cluster.test == 2)
test3 = subset(test, cluster.test == 3)
lm1 = lm(reimbursement2009 ~ ., data = train1)
lm2 = lm(reimbursement2009 ~ ., data = train2)
lm3 = lm(reimbursement2009 ~ ., data = train3)
summary(lm1)
summary(lm2)
summary(lm3)
pred.test1 = predict(lm1, newdata = test1)
pred.test2 = predict(lm2, newdata = test2)
pred.test3 = predict(lm3, newdata = test3)
mean(pred.test1)
mean(pred.test2)
mean(pred.test3)
#reference for rmse: sqrt(mean((test$reimbursement2009 - lm.testPred)^2))
#reference for rmse: sqrt(mean((test$reimbursement2009 - pred.test1)^2))
sqrt(mean((test$reimbursement2009 - pred.test1)^2))
sqrt(mean((test1$reimbursement2009 - pred.test1)^2))
sqrt(mean((test2$reimbursement2009 - pred.test2)^2))
sqrt(mean((test3$reimbursement2009 - pred.test3)^2))
all.predictions = c(pred.test1, pred.test2, pred.test3)
all.outcomes = c(test1$reimbursement2009, test2$reimbursement2009, test3$reimbursement2009)
sqrt(mean((all.predictions - all.outcomes)^2))
